#+STARTUP: indent
#+LATEX_CLASS: MOM
#+LATEX_CLASS_OPTIONS: [protection=SMP,aer=25337]
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \usepackage{longtable}
#+LATEX_HEADER: \renewcommand{\arraystretch}{1.3}
#+OPTIONS: toc:nil
#+OPTIONS: num:2
#+OPTIONS: title:nil

*  Thing I need to do still                                        :noexport:
** DONE count actions for ALL meetin
   CLOSED: [2017-10-01 dim. 14:30]
   - CLOSING NOTE [2017-10-01 dim. 14:30] \\
     done
** DONE Check hoe ik op verschillende plaatsen verschillende latex options kan gebruiken
   CLOSED: [2017-10-01 dim. 11:48]
   - CLOSING NOTE [2017-10-01 dim. 11:48] \\
     use latex varibles \def
** DONE copier alle acties in een nieuwe meeting
CLOSED: [2017-10-01 dim. 14:59]

** TODO make a table for participants
** TODO make a signature table

* Progress meeting n° 1
#+LATEX_HEADER: \def \crNumber {1}
#+LATEX_HEADER: \def \crRelease {12/5/2017}
** Attendees
  :PROPERTIES:
  :UNNUMBERED: t
  :END:      
- Marco de Rosa (ESA)
- Duc-mihn Le (ONERA)
- Anne-Julie Bougrine (LHCEP)
- Jouke Hijlkema (ONERA)

** Input
  :PROPERTIES:
  :UNNUMBERED: t
  :END:      
- DMAE/PR-25337-1 Progress report
- Hydrazine properties table (email from Anne-Julie 8/12/2016)
- MMH properties table (email from Anne-Julie 8/12/2016)

** Agenda
1. point on the structure of  progress report proposed by ONERA
2. point on the work done by LHCEP  on the hydrazine literature study
3. point on the work don by LHCPE on th MMH literature study
4. Divers

** Minutes

*** Point 1
ESA accepts the proposed template for the progress report. 
A new version will be edited for each progress meeting not containing the previous reports. 
The MOM for the progress reports need to be edited apart.

*** Point 2
LHCEP outlines the details of the table they composed based on literature data concerning Hydrazine. 
The main conclusion is that there are hardly any measurements, most data is compiled from a measurement campaign 
dating back 120 years. ESA is questioning the precision given on the Ultra sound measurements (6-12 m/s). 
This will be addressed during the calibration runs foreseen in WP 2.4

LHCEP will share information on a company specialised in high pressure measurement equipment.
ONERA will investigate the possibilities to ship small quantities of hydrazine (but also MMH, NTO and MON) to 
LHCEP so they can test the purity of the products. 
Ideally this should be done at regular intervals but at least at the beginning and the end of the test campaign.

*** Point 3
LHCEP outlines the details of the table they composed based on literature data concerning MMH.
The conclusions are similar to those for hydrazine. There exists very little measurements.
*** CLOSED 1 # Investigate the possibility to ship small quantities of hydrazine, MMH, NTO and MOM to Lyon to test the purity # resp ONERA # - # :noexport:
    CLOSED: [2017-10-01 dim. 14:42]
*** Point 4
ONERA and ESA will investigate the possibility to host an ftp server (or equivalent) to share articles and 
other documents between the partners of the project
*** CLOSED 2 # Investigate the possibility of an FTP server or similar to share documents amongst the partners # resp ONERA/ESA # - # :noexport:
    CLOSED: [2017-10-01 dim. 14:43]

    - CLOSING NOTE [2017-10-01 dim. 14:43] \\
      No real solution found

** Actions
# ActionTable
#+ATTR_LATEX: :environment longtable :align c|p{0.50\textwidth}|c|c|c
| Action      | Description                                        | responsible | due date | state |
|-------------+----------------------------------------------------+-------------+----------+-------|
|             | <50>                                               |             |          |       |
| DMAE-truc-1 | Investigate the possibility to ship small quantities of hydrazine, MMH, NTO and MOM to Lyon to test the purity | ONERA       | -        | C     |
| DMAE-truc-2 | Investigate the possibility of an FTP server or similar to share documents amongst the partners | ONERA/ESA   | -        | C     |

* Progress meeting n° 2
#+LATEX_HEADER: \def \crNumber {2}
#+LATEX_HEADER: \def \crRelease {12/5/2017}
  Date : 01-10-2017 :noexport:
** Attendees
   :PROPERTIES:
   :UNNUMBERED: 1
   :END: 
- Marco de Rosa (ESA)
- Jérôme Anthoie (ONERA)
- Dcu Minh LE (ONERA)
- Jouke Hijlkema [ONERA)

** Input
   :PROPERTIES:
   :UNNUMBERED: 1
   :END: 
!! A faire

** Agenda
!! A faire

** Minutes
blabla

** Conclusions

** Actions
   # ActionTable
   #+ATTR_LATEX: :environment longtable :align cp{0.60\textwidth}ccc
   | Action | Desiption                                          | responsible | due date | state |
   |--------+----------------------------------------------------+-------------+----------+-------|
   |        | <50>                                               |             |          |       |
