runcharts:
  - title: CPU & Memory
    position: [[0, 0], [45, 19]]
    rate-ms: 500
    legend:
        enabled: true
        details: false
    scale: 1
    items:
      - label: CPU
        color: 178
        sample: ps -A -o %cpu | awk '{s+=$1} END {print s}'
      - label: Memory
        sample:  ps -A -o %mem | awk '{s+=$1} END {print s}'
      - label: min
        color: 0
        sample: echo 0
      - label: max
        color: 0
        sample: echo 100
    
      
gauges:
  - title: YEAR PROGRESS
    position: [[45, 0], [35, 2]]
    cur:
        sample: date +%j
    max:
        sample: echo 365
    min:
        sample: echo 0
  - title: DAY PROGRESS
    position: [[45, 3], [35, 2]]
    cur:
        sample: date +%H
    max:
        sample: echo 24
    min:
        sample: echo 0
  - title: HOUR PROGRESS
    position: [[45, 6], [35, 2]]
    cur:
        sample: date +%M
    max:
        sample: echo 60
    min:
        sample: echo 0
  - title: MINUTE PROGRESS
    position: [[45, 9], [35, 2]]
    triggers:
      - title: CLOCK BELL EVERY MINUTE
        condition: '[ $label == "cur" ] && [ $cur -eq 0 ] && echo 1 || echo 0'
        actions:
            sound: true
            script: say -v samantha `date +%I:%M%p`
    cur:
        sample: date +%S
    max:
        sample: echo 60
    min:
        sample: echo 0
sparklines:
  - title: CPU usage
    position: [[0, 20], [22, 8]]
    rate-ms: 200
    scale: 0
    sample: ps -A -o %cpu | awk '{s+=$1} END {print s}'
textboxes:
  - title: Local weather
    position: [[0, 28], [13, 7]]
    rate-ms: 10000
    sample: curl wttr.in?0ATQF
    border: false
asciiboxes:
  - title: UTC time
    position: [[45, 12], [35, 7]]
    rate-ms: 500
    sample: env TZ=UTC date +%r
    border: false
    font: 2d
