;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-lt-gt
	c-electric-paren
	c-electric-semi&comma
	cua--prefix-override-handler
	cua-paste
	electric-newline-and-maybe-indent
	find-file
	keyboard-escape-quit
	mouse-save-then-kill
	mouse-set-region
	write-file
	))

(setq mc/cmds-to-run-once
      '(
	c-electric-colon
	c-electric-star
	eval-buffer
	ignore
	save-some-buffers
	tabbar-select-tab-callback
	toggle-comment-on-line
	))
