;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	TeX-insert-backslash
	c-electric-lt-gt
	c-electric-paren
	c-electric-semi&comma
	cua--prefix-override-handler
	cua-paste
	electric-newline-and-maybe-indent
	find-file
	keyboard-escape-quit
	mouse-save-then-kill
	mouse-set-region
	org-self-insert-command
	scroll-bar-toolkit-scroll
	wg-switch-to-workgroup-at-index-8
	write-file
	))

(setq mc/cmds-to-run-once
      '(
	c-electric-colon
	c-electric-star
	duplicate-line-or-region
	eval-buffer
	eval-print-last-sexp
	ignore
	indent-for-tab-command
	org-force-self-insert
	python-shell-send-buffer
	save-some-buffers
	tabbar-select-tab-callback
	toggle-comment-on-line
	wg-switch-to-workgroup-at-index-2
	yas-expand
	))
